### ISSUE TITLE
Mobile Friendly Interface

### ISSUE THREAD

**Issue by garudaonekh** [martinpihrt/OSPy#6]
Hi,
What is your suggestion to make this system mobile friendly?
I see you also have API section, is it a good idea to develop a separate Mobile App based on this API or simply update your UI and wrap it in a mobile framework?

Thanks;

**Comment by martinpihrt** [comment]
Hi,
I use the web interface (either on a PC or on a mobile phone) -> everything without any problems. Yes OSPy have the ability to use the API, here is the documentation: https://github.com/martinpihrt/OSPy/blob/master/api/docs/Details.md
If you can create an application, I'll be happy to add it to google play (I have a developer account) and to github.
There is already a mobile phone application from Samer (https://github.com/salbahra), but it is not compatible with OSPy -> maybe you can use it to get started for development.

https://github.com/OpenSprinkler/OpenSprinkler-App

Martin

**Comment by garudaonekh** [comment]
Yes, i have look at that mobile app by salbabra, but i think it is tightly integrated with their opensprinkler. Do you think it is a good idea to use that with your system? Yours has much more features.

**Comment by martinpihrt** [comment]
Their application will not work in the OSPy system. For some time I thought about using the application (a plugin would have to be made in the OSPy to convert the API from the OSPy and look like the Sip API). It would be a lot of work and as a result the application would not allow me to use all the functions that OSPy can do, because the application cannot. Of course, the author of the application does not add support for OSPy (he has no reason when using the opensprinkler). If you know how, you can build a completely new application for OSPy. I'll be happy to use it then.
Martin
